### ISSUE TITLE
No classes & no dismissing with Angular 1.3.8

### ISSUE THREAD

**Issue by aronduby** [rfink/angular-flare#3]
Love this module, used it a ton with Angular 1.2.0 Just started a project with 1.3.8 and the classes for the alerts are missing and you can't manually close them (but timer still works). The `classes` function never ends up getting called, so guessing something with the controller not getting associated right?

Fiddle showing the issue: http://jsfiddle.net/tv5wumas/1/ If I switch the angular version back to 1.2.0 it works great, but fails with 1.3.8

[updated full version numbers]

**Comment by rfink** [comment]
Hey, glad you like it!  I believe I see the problem, seems to be due to this bug in angular:

https://github.com/angular/angular.js/issues/9837

Only instead of ng-if, it's because of the ng-repeat on the root element being replaced.  It seems that this breaks isolate scope.  I'd still like to keep it isolated, to avoid any potential leaks.  I think the easiest fix would be to change "replace: true" to "replace: false", as that is deprecated in the future anyway.  This fixes the issue in 1.3.8 as well as continuing to work for 1.2.0.  I'm going to bump the version to 0.1, since this could potentially be a breaking change if someone has really specific CSS.

Thanks for pointing this out.  I have been away from front-end components for a little while, so I haven't had a chance to really dig into 1.3 yet.  Let me know if you find any other issues.

**Comment by rfink** [comment]
Fixed in #v0.1.0

**Comment by aronduby** [comment]
Good find on that bug and better fix than I hacked together. Still wrapping my head around custom directives. Thanks for the quick fix!
